services:
  postgres:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:?"DB_PASSWORD is required"}
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init/pg.sql:/docker-entrypoint-initdb.d/init.sql:ro,Z,U
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_data:
